create database template;

CREATE TABLE `USERS` (
  `USER_ID` varchar(50) NOT NULL DEFAULT '',
  `USER_PASSWORD` varchar(50) DEFAULT NULL,
  `FIRST_NAME` varchar(100) DEFAULT NULL,
  `LAST_NAME` varchar(100) DEFAULT NULL,
  `USER_EMAIL` varchar(100) DEFAULT NULL,
  `USER_TYPE` varchar(20) DEFAULT NULL,
  `VENDOR_ID` varchar(50) DEFAULT NULL,
  `MARKED_FOR_DELETE` varchar(1) DEFAULT NULL,
  `DEPARTMENT` varchar(50) DEFAULT NULL,
  `FAILED_LOGIN_ATTEMPTS` int(11) DEFAULT '0',
  `IS_ACCOUNT_LOCKED` varchar(1) DEFAULT NULL,
  `SITE_WORK_PHONE` varchar(25) DEFAULT NULL,
  `SITE_WORK_PHONE_ALT` varchar(25) DEFAULT NULL,
  `SITE_WORK_PHONE_EMG` varchar(25) DEFAULT NULL,
  `ACTIVE_TIME` int(5) DEFAULT NULL,
  `IS_TEMP_USER` varchar(1) DEFAULT NULL,
  `EXPIRED_ON` datetime DEFAULT NULL,
  `COMPANY_ID` varchar(50) DEFAULT NULL,
  `APPLICATION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
);

CREATE TABLE `ROLES` (
  `ROLE_ID` varchar(50) NOT NULL DEFAULT '',
  `ROLE_NAME` varchar(50) DEFAULT NULL,
  `APPLICATION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`)
);

CREATE TABLE `USER_ROLES` (
  `USER_ID` varchar(50) NOT NULL DEFAULT '',
  `ROLE_ID` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`USER_ID`,`ROLE_ID`),
  KEY `ROLE_ID` (`ROLE_ID`),
  CONSTRAINT `USER_ROLES_IBFK_1` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`),
  CONSTRAINT `USER_ROLES_IBFK_2` FOREIGN KEY (`ROLE_ID`) REFERENCES `roles` (`ROLE_ID`)
);

CREATE TABLE `LOGIN_HISTORY` (
  `HISTORY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(50) DEFAULT NULL,
  `ENTRY_TIMESTAMP` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `LOGIN_IP` varchar(50) DEFAULT NULL,
  `LOGIN_ACTION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`HISTORY_ID`)
);

INSERT INTO `ROLES` (`ROLE_ID`, `ROLE_NAME`, `APPLICATION`) VALUES ('ROLE_APP_USER', 'Application User', 'BASE');

INSERT INTO `USERS` (`USER_ID`, `USER_PASSWORD`, `FIRST_NAME`, `LAST_NAME`, `USER_EMAIL`, `USER_TYPE`, `VENDOR_ID`, `MARKED_FOR_DELETE`, `DEPARTMENT`, `FAILED_LOGIN_ATTEMPTS`, `IS_ACCOUNT_LOCKED`, `SITE_WORK_PHONE`, `SITE_WORK_PHONE_ALT`, `SITE_WORK_PHONE_EMG`, `ACTIVE_TIME`, `IS_TEMP_USER`, `EXPIRED_ON`, `COMPANY_ID`, `APPLICATION`) VALUES ('BHARAT', 'BHARAT', 'Bharat', 'Bhanderi', 'bbharatbhanderi.bb@gmail.com', 'USER', NULL, 'N', NULL, '0', 'N', '9999999999', '9999999999', '9999999999', NULL, NULL, NULL, 'TECHM', 'TELSTRA');


INSERT INTO `USER_ROLES` (`USER_ID`, `ROLE_ID`) VALUES ('BHARAT', 'ROLE_APP_USER');

